/**
 * fake-cli — a deterministic stand-in for a real coding agent. Driven by the mock
 * adapter (gated behind an explicit flag, never a user happy path) and also usable
 * as a plain `generic` adapter CLI in tests. It runs UNDER NODE inside a real PTY.
 *
 * This is plain `.mjs` on purpose (ADR-0011): Node's strip-types execution of a
 * `.ts` script inside a PTY is unreliable on the GitHub `windows-latest` runner, so
 * the node-executed script carries no TypeScript and no relative `.ts` imports. The
 * importable library source stays `.ts`; only this executed script is `.mjs`.
 *
 * The constants below are duplicated verbatim from `mock-protocol.ts` (the source
 * of truth); `fake-cli.protocol.test.ts` asserts they stay in lock-step.
 *
 * Behaviour: print a banner token, simulate a short "working" phase with periodic
 * output (so status stays `running`, never goes idle), write a real file into the
 * working dir (so the diff viewer has content later), print the done marker, and
 * exit 0 -> the terminal adapter infers `done` from the exit code.
 */
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { argv, cwd, exit, stdout } from "node:process";
import { setTimeout as delay } from "node:timers/promises";

// Mirror of mock-protocol.ts (kept in lock-step by fake-cli.protocol.test.ts).
const MOCK_OUTPUT_TOKEN = "SWARM-MOCK-AGENT";
const MOCK_DONE_MARKER = "__SWARM_MOCK_DONE__";
const MOCK_DEFAULT_FILENAME = "AGENT_OUTPUT.md";
const MOCK_FILE_HEADING = "# Swarm mock agent run";

function parseArgs(args) {
  let file = MOCK_DEFAULT_FILENAME;
  let workMs = 600;
  for (let i = 0; i < args.length; i += 1) {
    const flag = args[i];
    const value = args[i + 1];
    if (flag === "--file" && value !== undefined) {
      file = value;
      i += 1;
    } else if (flag === "--work-ms" && value !== undefined) {
      const parsed = Number(value);
      if (Number.isFinite(parsed) && parsed >= 0) {
        workMs = parsed;
      }
      i += 1;
    }
  }
  return { file, workMs };
}

function line(text) {
  stdout.write(`${text}\n`);
}

async function main() {
  const { file, workMs } = parseArgs(argv.slice(2));
  line(`${MOCK_OUTPUT_TOKEN} v1 starting in ${cwd()}`);

  const steps = 3;
  for (let step = 1; step <= steps; step += 1) {
    await delay(workMs / steps);
    line(`${MOCK_OUTPUT_TOKEN} working step ${step}/${steps}`);
  }

  const target = resolve(cwd(), file);
  const content = `${MOCK_FILE_HEADING}\n\nGenerated by ${MOCK_OUTPUT_TOKEN} after ${steps} steps.\n`;
  await writeFile(target, content, "utf8");
  line(`${MOCK_OUTPUT_TOKEN} wrote ${file}`);
  line(`${MOCK_DONE_MARKER} ${file}`);
  return 0;
}

main().then(
  (code) => exit(code),
  (error) => {
    const reason = error instanceof Error ? error.message : String(error);
    line(`${MOCK_OUTPUT_TOKEN} failed: ${reason}`);
    exit(1);
  },
);
