/**
 * fake-cli — a deterministic stand-in for a real coding agent, used ONLY by the
 * mock adapter (which is gated behind an explicit flag, never a user happy path).
 * It runs UNDER NODE inside a real PTY (Node 24 strips the type annotations), so
 * the integration/e2e suite can exercise the full spawn -> stream -> file-change
 * -> done path with no real CLI and no API key.
 *
 * Behaviour: print a banner token, simulate a short "working" phase with periodic
 * output (so status stays `running`, never goes idle), write a real file into the
 * working dir (so the diff viewer has content later), print the done marker, and
 * exit 0 -> the terminal adapter infers `done` from the exit code.
 */
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { argv, cwd, exit, stdout } from "node:process";
import { setTimeout as delay } from "node:timers/promises";
import {
  MOCK_DEFAULT_FILENAME,
  MOCK_DONE_MARKER,
  MOCK_FILE_HEADING,
  MOCK_OUTPUT_TOKEN,
} from "./mock-protocol.ts";

interface Parsed {
  readonly file: string;
  readonly workMs: number;
}

function parseArgs(args: readonly string[]): Parsed {
  let file = MOCK_DEFAULT_FILENAME;
  let workMs = 600;
  for (let i = 0; i < args.length; i += 1) {
    const flag = args[i];
    const value = args[i + 1];
    if (flag === "--file" && value !== undefined) {
      file = value;
      i += 1;
    } else if (flag === "--work-ms" && value !== undefined) {
      const parsed = Number(value);
      if (Number.isFinite(parsed) && parsed >= 0) {
        workMs = parsed;
      }
      i += 1;
    }
  }
  return { file, workMs };
}

function line(text: string): void {
  stdout.write(`${text}\n`);
}

async function main(): Promise<number> {
  const { file, workMs } = parseArgs(argv.slice(2));
  line(`${MOCK_OUTPUT_TOKEN} v1 starting in ${cwd()}`);

  const steps = 3;
  for (let step = 1; step <= steps; step += 1) {
    await delay(workMs / steps);
    line(`${MOCK_OUTPUT_TOKEN} working step ${step}/${steps}`);
  }

  const target = resolve(cwd(), file);
  const content = `${MOCK_FILE_HEADING}\n\nGenerated by ${MOCK_OUTPUT_TOKEN} after ${steps} steps.\n`;
  await writeFile(target, content, "utf8");
  line(`${MOCK_OUTPUT_TOKEN} wrote ${file}`);
  line(`${MOCK_DONE_MARKER} ${file}`);
  return 0;
}

main().then(
  (code) => exit(code),
  (error: unknown) => {
    const reason = error instanceof Error ? error.message : String(error);
    line(`${MOCK_OUTPUT_TOKEN} failed: ${reason}`);
    exit(1);
  },
);
