import { cn } from "@swarm/ui";
import { AgentStatusDot, BottomNav, Button, EmptyState } from "@swarm/ui/react";
import { Boxes, GitCompare, Smartphone, TerminalSquare } from "lucide-react";
import { useMemo, useState } from "react";
import { Section } from "../components/Section";
import { useAgents, useDispatch, usePaired, useSelectedId } from "../store/cockpit";

const PHONE_NAV = [
  { id: "swarm", label: "Swarm", icon: <Boxes /> },
  { id: "terminal", label: "Terminal", icon: <TerminalSquare /> },
  { id: "diff", label: "Diff", icon: <GitCompare /> },
];

export function Phone() {
  const paired = usePaired();
  const dispatch = useDispatch();

  return (
    <Section
      id="phone"
      num="06"
      title="Pair the phone, keep watching"
      subhead="The desktop hosts a small PWA you pair over loopback with a bearer token — the QR is generated by the running app, on your machine. Once paired, the phone is the same cockpit bound to the same state: tap an agent here and the desktop rail updates. No account, no cloud, no network leaving the box."
    >
      <div className="grid items-start gap-6 lg:grid-cols-[1fr_auto]">
        {/* QR panel — a labeled sample, never a fabricated scannable code. */}
        <div className="overflow-hidden rounded-lg border border-line bg-surface">
          <div className="border-b border-line px-3 py-2">
            <span className="font-mono text-2xs uppercase tracking-wide text-fg-subtle">
              pair over loopback
            </span>
          </div>
          <div className="flex flex-col items-start gap-4 p-4 sm:flex-row sm:items-center">
            <SampleQr />
            <div className="min-w-0">
              <p className="font-mono text-xs text-fg-muted">grove://loopback:7433/pair</p>
              <p className="mt-1 font-mono text-2xs text-fg-subtle">
                bearer-gated · token rotates per session
              </p>
              <p className="mt-2 max-w-xs text-xs text-fg-muted">
                Labeled sample — not a scannable code. The real QR is rendered by the desktop app
                from your loopback host and bearer token.
              </p>
              <div className="mt-3">
                <Button
                  variant={paired ? "secondary" : "primary"}
                  icon={<Smartphone className="size-3.5" />}
                  onClick={() => dispatch({ type: "pair", paired: !paired })}
                >
                  {paired ? "Unpair phone" : "Pair phone"}
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* To-scale phone frame. */}
        <PhoneFrame nav={PHONE_NAV} />
      </div>
    </Section>
  );
}

/**
 * A deterministic decorative QR-like mark — clearly a sample, NOT a working
 * code. A fixed bit pattern (no randomness, SSR-stable) with the three finder
 * eyes, rendered on-token. It exists to read as "a QR goes here", honestly
 * labeled, never to be scanned.
 */
function SampleQr() {
  const N = 11;
  const cells = useMemo(() => {
    const out: boolean[] = [];
    for (let i = 0; i < N * N; i++) {
      const r = Math.floor(i / N);
      const c = i % N;
      // Finder eyes in three corners.
      const eye = (br: number, bc: number) => r >= br && r < br + 3 && c >= bc && c < bc + 3;
      if (eye(0, 0) || eye(0, N - 3) || eye(N - 3, 0)) {
        const inRing =
          r === 0 ||
          r === 2 ||
          c === 0 ||
          c === 2 ||
          r === N - 3 ||
          r === N - 1 ||
          c === N - 3 ||
          c === N - 1;
        out.push(inRing || r % 2 === c % 2);
      } else {
        // A fixed checker-ish field — stable, meaningless, clearly a sample.
        out.push((r * 7 + c * 3) % 5 === 0 || (r + c) % 3 === 0);
      }
    }
    return out;
  }, []);

  return (
    <div
      className="grid shrink-0 gap-px rounded-md border border-line bg-base p-2"
      style={{ gridTemplateColumns: `repeat(${N}, 0.5rem)` }}
      role="img"
      aria-label="Sample pairing QR — illustrative, not scannable"
    >
      {cells.map((on, i) => (
        <span
          // biome-ignore lint/suspicious/noArrayIndexKey: fixed, ordered sample grid
          key={i}
          className={cn("size-2 rounded-[1px]", on ? "bg-fg" : "bg-transparent")}
        />
      ))}
    </div>
  );
}

function PhoneFrame({
  nav,
}: {
  readonly nav: readonly { id: string; label: string; icon: React.ReactNode }[];
}) {
  const paired = usePaired();
  const agents = useAgents();
  const dispatch = useDispatch();
  const selectedId = useSelectedId();
  const [tab, setTab] = useState("swarm");

  return (
    <div className="mx-auto w-[300px] max-w-full">
      <div className="overflow-hidden rounded-[2rem] border-[6px] border-line-strong bg-base shadow-sm">
        <div className="flex h-[600px] flex-col">
          <header className="flex h-12 shrink-0 items-center gap-2 border-b border-line bg-surface px-4">
            <span className="font-mono text-sm font-medium text-fg">grove</span>
            <span className="font-mono text-2xs text-fg-subtle">
              {paired ? "loopback · paired" : "not paired"}
            </span>
          </header>

          <div className="min-h-0 flex-1 overflow-auto">
            {!paired ? (
              <EmptyState
                icon={<Smartphone />}
                title="Locked"
                description="Pair from the desktop QR to bind this phone to the running cockpit."
                hint="grove://loopback:7433/pair"
                className="h-full"
              />
            ) : (
              <ul className="flex flex-col gap-0.5 p-2">
                {agents.slice(0, 8).map((a) => (
                  <li key={a.id}>
                    <button
                      type="button"
                      aria-current={selectedId === a.id ? "true" : undefined}
                      onClick={() => dispatch({ type: "select", id: a.id })}
                      className={cn(
                        "flex w-full items-center gap-2 rounded-md px-2 py-2 text-left transition-colors duration-fast",
                        selectedId === a.id
                          ? "bg-accent-bg ring-1 ring-inset ring-accent-border"
                          : "hover:bg-raised",
                      )}
                    >
                      <AgentStatusDot status={a.status} />
                      <span className="min-w-0 flex-1 truncate font-mono text-xs text-fg">
                        {a.branch}
                      </span>
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>

          <BottomNav items={nav} value={tab} onChange={setTab} aria-label="Phone sections" />
        </div>
      </div>
      <p className="mt-2 text-center font-mono text-2xs text-fg-subtle">
        {paired ? "tap an agent — the desktop rail updates" : "to-scale · 300px"}
      </p>
    </div>
  );
}
